package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class AgentShipInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.agentName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String agentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.zhName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String zhname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.enName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String enname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.mmsi
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.nationality
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.callSign
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String callsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.Imo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String imo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.shipType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.shipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.shipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.totalTonNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer totaltonnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.netTonNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer nettonnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.loadTonNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer loadtonnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.aboutport
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String aboutport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.prearrivaltime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String prearrivaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agentshipinfo.predeparttime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String predeparttime;
}