package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthinInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.Direction
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.Length
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.ForwardDepth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String forwarddepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.DockBasinDepth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dockbasindepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.MeasureDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String measuredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.Company
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.AreaName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthinfo.BerthedBoatInfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthedboatinfo;

}