package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthPos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.PortName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String portname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.Anchor
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String anchor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.Longitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.Latitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.lon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double lon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.lat
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.lineID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer lineid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthpos.lineName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String linename;

}