package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthStateType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstatetype.BerthStateCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthstatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstatetype.BerthState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthstate;
}