package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthPlanHistoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.BerthPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.PlanDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String plandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.ShipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.DeadWeightTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double deadweightton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.CurrentState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String currentstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.OperationCompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.PreBerthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date preberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.PreUnberthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date preunberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.LoadorUnLoad
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String loadorunload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.PreLoad
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double preload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.CompanyOdrTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date companyodrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.CompanyOdrBerth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String companyodrberth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.RecordTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplanhistoryinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;

}