package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthStateRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstaterecord.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstaterecord.BerthID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstaterecord.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstaterecord.BerthState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthstaterecord.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date updatetime;

}