package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class BerthPlanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.BerthPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.PlanDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String plandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.ShipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.DeadWeightTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double deadweightton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.CurrentState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String currentstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.OperationCompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.PreBerthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date preberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.PreUnberthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date preunberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.LoadorUnLoad
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String loadorunload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.PreLoad
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double preload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.CompanyOdrTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date companyodrtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.CompanyOdrBerth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String companyodrberth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column berthplaninfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;

}