package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class CdqrImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.VoyageId
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.TugPlanId
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.UserName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.ShipAgent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.CDQRImage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String cdqrimage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdqrimage.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}