package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ChargeStandardInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargestandardinfo.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargestandardinfo.ChargeStandard
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargestandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargestandardinfo.OperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargestandardinfo.ChargeStandardMsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargestandardmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chargestandardinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}