package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class CostInfoToInvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.formNumber
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String formnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.tugApplyId
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.state
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.requestTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String requesttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.uuid
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.isEstimate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isestimate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costinfotoinvoice.body
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String body;
}