package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class CreditProofImage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.ShipAgent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.ImagePath
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column creditproofimage.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}