package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class DataAlarmInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.AlarmID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.HangBiaoXH
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String hangbiaoxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.DataID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.DataValue
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double datavalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.AlarmDesc
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String alarmdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.AlarmLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.StartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.EndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.AlarmRespond
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmrespond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.RespondTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date respondtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dataalarminfo.Operater
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operater;
}