package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class DataInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.DataID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.HangBiaoXH
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String hangbiaoxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.DataName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dataname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.DataVal
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double dataval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmItem
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer alarmlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmDesc
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String alarmdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmStartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date alarmstarttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmEndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date alarmendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.AlarmRespond
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String alarmrespond;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.RespondTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date respondtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.Operater
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datainfo.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;
}