package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class DataHistoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datahistoryinfo.DataStoreID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer datastoreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datahistoryinfo.HangBiaoXH
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String hangbiaoxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datahistoryinfo.DataID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dataid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datahistoryinfo.DataVal
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double dataval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column datahistoryinfo.StoreTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String storetime;
}