package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class DispatcherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.dispatcher
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatcher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.text
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dispatcherinfo.reserve4
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve4;
}