package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class EpidemicMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.Apply14Num
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer apply14num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.Apply14Place
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String apply14place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.Port14
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String port14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.Other
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String other;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epidemicmsg.ZJChange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String zjchange;
}