package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ExceptionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.exec_id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String execId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.exc_name
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String excName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_user_id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_user_name
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_method
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_uri
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_ip
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.oper_create_time
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date operCreateTime;
}