package com.whut.wharf.entity;

import lombok.*;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class ExceptionLogWithBLOBs extends ExceptionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.exec_requ_param
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String execRequParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exceptionlog.exc_message
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String excMessage;
}