package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ExpenseTypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.expensetype
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String expensetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.taxrate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Float taxrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.EnglishName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String englishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.CommodityCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String commoditycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.Unit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.Specifications
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.TaxClassificationCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String taxclassificationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.ZeroTaxMark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String zerotaxmark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.TaxVersion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String taxversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.PreferentialPolicies
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String preferentialpolicies;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.TaxRelief
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String taxrelief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expensetypeinfo.Price
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String price;
}