package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class FairwayInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.FairwayID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer fairwayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.FairwayName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String fairwayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.FairwayProperty
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String fairwayproperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.WaterDepth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double waterdepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fairwayinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}