package com.whut.wharf.entity;

import lombok.*;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class NoticeWithBLOBs extends Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.content
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.readPeople
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String readpeople;
}