package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class OperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_modul
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operModul;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_type
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_desc
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_user_id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_user_name
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_method
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_uri
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_ip
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_create_time
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date operCreateTime;
}