package com.whut.wharf.entity;

import lombok.*;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class OperationLogWithBLOBs extends OperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_requ_param
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operRequParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationlog.oper_resp_param
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operRespParam;
}