package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class OperationDispatchMsg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.DispatchID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.DispatchTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.OperationArea
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.OperationBerth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationberth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.OperationName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.TugNumbers
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer tugnumbers;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.IsFinished
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isfinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operationdispatchmsg.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;
}