package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class PilotPlanHistoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.PioltPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String pioltplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.MaxDraft
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double maxdraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.ShipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.ShipType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.PilotPerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String pilotperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.InShipWay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.IsNeedTug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isneedtug;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.TugNumber
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer tugnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.InShipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date inshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.InShipDes
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.ExecutionState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String executionstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.RecordTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pilotplanhistoryinfo.planDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String plandate;
}