package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class PlotAreaInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.AreanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer areanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.AreaName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.AreaType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer areatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.AreaDesc
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String areadesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.Longitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.Latitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.StartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plotareainfo.EndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date endtime;
}