package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class PortRegisterInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.StartPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String startport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.DestPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String destport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.PrePort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String preport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.NextPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String nextport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.PreArrivalTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String prearrivaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.PreDepartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String predeparttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.PlanBerthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String planberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.PlanUnberthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String planunberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.TradeType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}