package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class PortRegisterInfoCopy1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.StartPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String startport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.DestPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String destport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.PrePort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String preport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.NextPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String nextport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.PreArrivalTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String prearrivaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.PreDepartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String predeparttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.PlanBerthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String planberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.PlanUnberthTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String planunberthtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.TradeType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column portregisterinfo_copy1.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}