package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ReceiptBasicInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SAcompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.TaxNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String taxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.IsCom
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String iscom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.Address
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.Phone
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.BankName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.BankNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String banknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SaleParty
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String saleparty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.Code
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SaleAddress
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String saleaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SalePhone
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String salephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SaleBank
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String salebank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.SaleBankNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String salebanknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column receiptbasicinfo.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;
}