package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ShipTeamInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipteaminfo.teamID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipteaminfo.teamName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String teamname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipteaminfo.showColor
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String showcolor;
}