package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ShipInTeam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipinteam.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipinteam.teamID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipinteam.ChineseName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chinesename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipinteam.EnglishName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String englishname;
}