package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ShipTraceInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipCallNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipcallnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipDraft
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipdraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipnType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer shipntype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.Latitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.Longitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.Speed
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.ShipAngle
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.TraceAngle
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double traceangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.dynState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer dynstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shiptraceinfo.lTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer ltime;
}