package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class ShipOperationData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.isHead
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer ishead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.specificTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String specifictime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.timeType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer timetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shipoperationdata.jsonData
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jsondata;
}