package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class StateTypeInport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statetypeinport.InportStateCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inportstatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column statetypeinport.InportState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inportstate;
}