package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TestA {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_a.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_a.a
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_a.b
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_a.c
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String c;
}