package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugApplyInorExportInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.AboutPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String aboutport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.LoadorUnload
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String loadorunload;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.CargoTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double cargoton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.ArrivalDraftF
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double arrivaldraftf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.ArrivalDraftB
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double arrivaldraftb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.DepartDraftF
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double departdraftf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.DepartDraftB
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double departdraftb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplyinorexportinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}