package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugApplyMsgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ApplyDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String applydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ProposerName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String proposername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ProposerType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String proposertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ChineseName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chinesename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.EnglishName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String englishname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.SiCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sicode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.SACompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ApplyUnit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String applyunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.PayUnit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String payunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.IsRespAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isrespagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.RespAgreeMsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String respagreemsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.SACertification
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacertification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ShipMSG
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ProposerSign
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String proposersign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.AuditState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String auditstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.DispatchState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.ChargeState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.AuditDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String auditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String pilotinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.dispatchOperator
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchoperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.revokeState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String revokestate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.tradeType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tradetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.NameVisible
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String namevisible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.confirmRemark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String confirmremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.shipTel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugapplymsginfo.TugChangeMsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugchangemsg;
}