package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugBerthCost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.lengthMin
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer lengthmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.lengthMax
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer lengthmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.type
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.nation
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthcost.cost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer cost;
}