package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugBerthNum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.lengthMin
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer lengthmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.lengthMax
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer lengthmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.DraftMin
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer draftmin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.DraftMax
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer draftmax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.type
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.Nums
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer nums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.tugType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer tugtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugberthnum.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}