package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugCostInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.voyageId
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ShipType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.RouteType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String routetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.TugNums
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer tugnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.Costs
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double costs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.IsCharging
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ischarging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.IsAudit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.IsAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ChargingType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargingtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ChargeDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ShiptypeCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.ChargingPer
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargingper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.CheckPer
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String checkper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostinfo.RealCosts
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double realcosts;
}