package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugCostConsultInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.Costs
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double costs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.RealCosts
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double realcosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.IsCharging
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ischarging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.IsAudit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.IsAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.ChargeType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.ChargingPer
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargingper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.CheckPer
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String checkper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.AffirmPer
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String affirmper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.Reasons
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.Time
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugcostconsultinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}