package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugChargeMsgInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.AuditDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String auditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.OpeNums
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer openums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.CalculateCosts
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double calculatecosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.RealCosts
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double realcosts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.CurState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String curstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.IsAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.ChargePerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargeperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.CheckPerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String checkperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SAInfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sainfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SASign
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sasign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.operationMkeyList
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationmkeylist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.isSplit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Byte issplit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SendState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sendstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SAPerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String saperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.Extras
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String extras;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.ExtraType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String extratype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.processState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String processstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SACostList
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacostlist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.SACostSign
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacostsign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.filecode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String filecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.dateList
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String datelist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.saveFhTimeNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String savefhtimenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.invoiceType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String invoicetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.sendToFinanceTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sendtofinancetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.expensetype
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String expensetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.costinfosentdate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String costinfosentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.chargedate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chargedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.checkdate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String checkdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.FhTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String fhtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.isreturn
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer isreturn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.saremark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String saremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugchargemsginfo.Reasons
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reasons;
}