package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugDispatchDriverInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.Driver
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.DriverTel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String drivertel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.Reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.Reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.Reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugdispatchdriverinfo.crewPosition
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String crewposition;
}