package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugInfoDispatchDel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.DispatchID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.DispatchTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.BCTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String bctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.QMTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String qmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.DTTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.JTTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.YSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ystime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.JHTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jhtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.XMTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String xmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.KSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String kstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.JSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.WCTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String wctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.FinishTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String finishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.SubmitTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.Scores
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double scores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.IsAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.Reasons
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.scoreAudit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String scoreaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.receiver
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchdel.isExtraCharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isextracharge;
}