package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.MKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.BuildDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String builddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.GrossTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String grosston;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Power
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Model
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.TugType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Length
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Width
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Height
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Speed
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double speed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Illustration
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String illustration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.TugState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.StateCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String statecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.abbr
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String abbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.RegisterTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.orderNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer ordernum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfo.UseWay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String useway;
}