package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugInfoDispatchTmp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchtmp.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchtmp.DispatchID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchtmp.DispatchTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatchtmp.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;
}