package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugInfoDispatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.DispatchID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.DispatchTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dispatchtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.BCTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String bctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.QMTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String qmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.DTTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.JTTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.YSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ystime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.JHTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jhtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.XMTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String xmtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.KSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String kstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.JSTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String jstime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.WCTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String wctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.FinishTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String finishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.SubmitTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.Scores
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double scores;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.IsAgree
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isagree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.Reasons
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.scoreAudit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String scoreaudit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.receiver
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.isExtraCharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isextracharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tuginfodispatch.TugCost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double tugcost;
}