package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugOperationInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TugOperationID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.IsStay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isstay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TugOperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.StartPosition
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String startposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.EndPosition
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String endposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.StartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.DraftTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date drafttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.UnshipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date unshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.EndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TugOperationTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date tugoperationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.AssistTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date assisttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.ChargeTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date chargetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.RealCost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double realcost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.ProtocolNum
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String protocolnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.AllInRate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double allinrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.DayOrNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dayornight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.IsRemoteDraft
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isremotedraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.IsHoliday
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isholiday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.HorsePower
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double horsepower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.AjustHorsePower
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double ajusthorsepower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.Dirver
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dirver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.OperationDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.TradeIntFor
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tradeintfor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.InOrOutPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inoroutport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.IsHeadOffice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String isheadoffice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.CheckTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.GeneratListTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date generatlisttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.ListTransferTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date listtransfertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.PrintTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date printtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}