package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugOperationTypeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationtypeinfo.TugOperTypeCode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugopertypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugoperationtypeinfo.TugOperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtype;
}