package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugProposerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.TugApplyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugapplyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.ProposerName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String proposername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.ProposerTel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String proposertel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.IdentifyID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String identifyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.SACompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugproposerinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}