package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugPlanHistoryInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.TugOperationArea
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.TugOperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.GoBerth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String goberth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.StartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.DraftTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date drafttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.UnshipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date unshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.EndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.TugOperationTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.DayOrNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dayornight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.ApplyTugNums
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer applytugnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.RateStandard
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ratestandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.InShipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date inshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.InShipDes
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.PilotPerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String pilotperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.OperationWorker
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationworker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.RouteType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String routetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.CreditLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String creditlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.ExecutionState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String executionstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.RecordTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date recordtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.InShipWay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplanhistoryinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}