package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugPlanInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.VoyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.PlanDate
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String plandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.TugOperationArea
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.TugOperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.GoBerth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String goberth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.StartTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.DraftTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date drafttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.UnshipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date unshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.EndTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.TugOperationTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.DayOrNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dayornight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ApplyTugNums
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer applytugnums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.RateStandard
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String ratestandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.InShipTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date inshiptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.InShipDes
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipdes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.PilotPerson
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String pilotperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.OperationWorker
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationworker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.MMSI
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mmsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ChineseName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String chinesename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.Nationality
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipLength
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shiplength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipWidth
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double shipwidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.maxDraft
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double maxdraft;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.RouteType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String routetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.DeadweightTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double deadweightton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.GrossTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double grosston;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.NetTon
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double netton;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.PreviousPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String previousport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.NextPort
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String nextport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipOwner
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ShipAgent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipagent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.CreditLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String creditlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.ExecutionState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String executionstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.InShipWay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String inshipway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugplaninfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}