package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugScoreInfoCopy1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.MKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.Company
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.OperationName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.UnStayDay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String unstayday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.UnStayNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String unstaynight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.StayDay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String stayday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.StayNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String staynight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo_copy1.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}