package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugStateChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.tuginfoMkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer tuginfomkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.tugState
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugstate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.updateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugstatechange.reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;
}