package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugScoreInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.MKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.BerthName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String berthname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.Company
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.OperationName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String operationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.UnStayDay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String unstayday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.UnStayNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String unstaynight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.StayDay
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String stayday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.StayNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String staynight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugscoreinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;
}