package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class TugWokerPoints {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.TugPlanID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugplanid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.voyageID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String voyageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.WorkerID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String workerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.WorkerName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String workername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.Position
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.TugOperationType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugoperationtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.DayOrNight
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String dayornight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tugwokerpoints.Points
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double points;
}