package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UnionFull {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.TugName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String tugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.Driver
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.DriverTel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String drivertel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.Reserve1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.Reserve2
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.Reserve3
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unionfull.crewPosition
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String crewposition;
}