package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import java.util.Date;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UserLogInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.logkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer logkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.userid
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.accountName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String accountname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.logtime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Date logtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.loglIP
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String loglip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userloginfo.logresult
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String logresult;
}