package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.id
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.user_mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer userMkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_mKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer roleMkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.isSa
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Byte issa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.isZgt
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Byte iszgt;
}