package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UserInfoTug {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.MKey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.UserName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.Password
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.UserType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfotug.isEnabled
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Byte isenabled;
}