package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Password
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserOrg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String userorg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ShipAgentCredit
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipagentcredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ShipAgentOwner
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String shipagentowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.Reserve
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String reserve;
}