package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class UserInfoSa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.Mkey
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer mkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.UserName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.Password
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.SACompany
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String sacompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.Remark
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.signature
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String signature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.phone
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.idCard
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.disable
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String disable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.isEnabled
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Byte isenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfosa.UserType
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String usertype;
}