package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class WeatherInfoHis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.WeatherNumber
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer weathernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.StationID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.WindSpeed
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.WindLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String windlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.WindAngle
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.WindDirect
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String winddirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.VisibleLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double visiblelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.Temperature
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.Humidity
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.Pm10
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double pm10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.Pressure
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.Rain
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double rain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohis.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;
}