package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class WeatherInfoHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.WeatherNumber
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer weathernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.WindLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String windlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.InfulenceArea
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String infulencearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.InfulenceTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String infulencetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.VisibleLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String visiblelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Temperature
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Longitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Latitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Pm10
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double pm10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Humidity
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.AtmosphericPressure
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double atmosphericpressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.WindSpeed
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.Wind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String wind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.WindAngle
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfohistory.State
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String state;
}