package com.whut.wharf.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@ToString
@NoArgsConstructor
@AllArgsConstructor
public class WeatherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.StationID
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Integer stationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.StationName
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Longitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Latitude
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.WindSpeed
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.WindLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String windlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.WindAngle
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double windangle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.WindDirect
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String winddirect;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.VisibleLevel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double visiblelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Temperature
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Humidity
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double humidity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Pm10
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double pm10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Pressure
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double pressure;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.Rain
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private Double rain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weatherinfo.UpdateTime
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    private String updatetime;
}