package com.whut.wharf.mapper;

import com.whut.wharf.entity.AnchorInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("anchorInfoMapper")
public interface AnchorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String anchorname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(AnchorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(AnchorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    AnchorInfo selectByPrimaryKey(String anchorname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(AnchorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anchorinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(AnchorInfo record);
}