package com.whut.wharf.mapper;

import com.whut.wharf.entity.Appversion;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("appversionMapper")
public interface AppversionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    Appversion selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Appversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appversion
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(Appversion record);
}