package com.whut.wharf.mapper;

import com.whut.wharf.entity.AreaInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("areaInfoMapper")
public interface AreaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String areaname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    AreaInfo selectByPrimaryKey(String areaname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(AreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table areainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(AreaInfo record);
}