package com.whut.wharf.mapper;

import com.whut.wharf.entity.BerthPlanHistoryInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("berthPlanHistoryInfoMapper")
public interface BerthPlanHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(BerthPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(BerthPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    BerthPlanHistoryInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(BerthPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(BerthPlanHistoryInfo record);
}