package com.whut.wharf.mapper;

import com.whut.wharf.entity.BerthPlanInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("berthPlanInfoMapper")
public interface BerthPlanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String berthplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(BerthPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(BerthPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    BerthPlanInfo selectByPrimaryKey(String berthplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(BerthPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table berthplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(BerthPlanInfo record);
}