package com.whut.wharf.mapper;

import com.whut.wharf.entity.CdqrImage;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("cdqrImageMapper")
public interface CdqrImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(CdqrImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(CdqrImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    CdqrImage selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(CdqrImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdqrimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(CdqrImage record);
}