package com.whut.wharf.mapper;

import com.whut.wharf.entity.ChargeStandardInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("chargeStandardInfoMapper")
public interface ChargeStandardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ChargeStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ChargeStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ChargeStandardInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ChargeStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ChargeStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chargestandardinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ChargeStandardInfo record);
}