package com.whut.wharf.mapper;

import com.whut.wharf.entity.ClientToCode;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("clientToCodeMapper")
public interface ClientToCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttocode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ClientToCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttocode
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ClientToCode record);
}