package com.whut.wharf.mapper;

import com.whut.wharf.entity.CostInfoToInvoice;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("costInfoToInvoiceMapper")
public interface CostInfoToInvoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(CostInfoToInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(CostInfoToInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    CostInfoToInvoice selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(CostInfoToInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(CostInfoToInvoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table costinfotoinvoice
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(CostInfoToInvoice record);
}