package com.whut.wharf.mapper;

import com.whut.wharf.entity.CreditProofImage;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("creditProofImageMapper")
public interface CreditProofImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(CreditProofImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(CreditProofImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    CreditProofImage selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(CreditProofImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table creditproofimage
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(CreditProofImage record);
}