package com.whut.wharf.mapper;

import com.whut.wharf.entity.DataHistoryInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("dataHistoryInfoMapper")
public interface DataHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer datastoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(DataHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(DataHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    DataHistoryInfo selectByPrimaryKey(Integer datastoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(DataHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table datahistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(DataHistoryInfo record);
}