package com.whut.wharf.mapper;

import com.whut.wharf.entity.EpidemicMsg;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("epidemicMsgMapper")
public interface EpidemicMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(EpidemicMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(EpidemicMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    EpidemicMsg selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(EpidemicMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epidemicmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(EpidemicMsg record);
}