package com.whut.wharf.mapper;

import com.whut.wharf.entity.ExceptionLog;
import com.whut.wharf.entity.ExceptionLogWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("exceptionLogMapper")
public interface ExceptionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String execId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ExceptionLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ExceptionLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ExceptionLogWithBLOBs selectByPrimaryKey(String execId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ExceptionLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ExceptionLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exceptionlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ExceptionLog record);
}