package com.whut.wharf.mapper;

import com.whut.wharf.entity.ExpenseTypeInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("expenseTypeInfoMapper")
public interface ExpenseTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expensetypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ExpenseTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expensetypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ExpenseTypeInfo record);
}