package com.whut.wharf.mapper;

import com.whut.wharf.entity.ExtraCharge;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("extraChargeMapper")
public interface ExtraChargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ExtraCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ExtraCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ExtraCharge selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ExtraCharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extracharge
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ExtraCharge record);
}