package com.whut.wharf.mapper;

import com.whut.wharf.entity.FairwaySideLineInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("fairwaySideLineInfoMapper")
public interface FairwaySideLineInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(FairwaySideLineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(FairwaySideLineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    FairwaySideLineInfo selectByPrimaryKey(Integer lineid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(FairwaySideLineInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelineinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(FairwaySideLineInfo record);
}