package com.whut.wharf.mapper;

import com.whut.wharf.entity.FairwaySideLinePointInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("fairwaySideLinePointInfoMapper")
public interface FairwaySideLinePointInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer pointnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(FairwaySideLinePointInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(FairwaySideLinePointInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    FairwaySideLinePointInfo selectByPrimaryKey(Integer pointnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(FairwaySideLinePointInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwaysidelinepointinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(FairwaySideLinePointInfo record);
}