package com.whut.wharf.mapper;

import com.whut.wharf.entity.FairwayInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("fairwayInfoMapper")
public interface FairwayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer fairwayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(FairwayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(FairwayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    FairwayInfo selectByPrimaryKey(Integer fairwayid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(FairwayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fairwayinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(FairwayInfo record);
}