package com.whut.wharf.mapper;

import com.whut.wharf.entity.ForecastCorrespondInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("forecastCorrespondInfoMapper")
public interface ForecastCorrespondInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyidold);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ForecastCorrespondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ForecastCorrespondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ForecastCorrespondInfo selectByPrimaryKey(String tugapplyidold);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ForecastCorrespondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecastcorrespondinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ForecastCorrespondInfo record);
}