package com.whut.wharf.mapper;

import com.whut.wharf.entity.HangBiaoInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("hangBiaoInfoMapper")
public interface HangBiaoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String hangbiaoxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(HangBiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(HangBiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    HangBiaoInfo selectByPrimaryKey(String hangbiaoxh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(HangBiaoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hangbiaoinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(HangBiaoInfo record);
}