package com.whut.wharf.mapper;

import com.whut.wharf.entity.IdIdentify;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("idIdentifyMapper")
public interface IdIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ididentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String idsave);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ididentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(IdIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ididentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(IdIdentify record);
}