package com.whut.wharf.mapper;

import com.whut.wharf.entity.MergingTugCalculateInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("mergingTugCalculateInfoMapper")
public interface MergingTugCalculateInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(MergingTugCalculateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(MergingTugCalculateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    MergingTugCalculateInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(MergingTugCalculateInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mergingtugcalculateinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(MergingTugCalculateInfo record);
}