package com.whut.wharf.mapper;

import com.whut.wharf.entity.OperationDispatchMsgDel;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("operationDispatchMsgDelMapper")
public interface OperationDispatchMsgDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsgdel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(OperationDispatchMsgDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsgdel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(OperationDispatchMsgDel record);
}