package com.whut.wharf.mapper;

import com.whut.wharf.entity.OperationDispatchMsg;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("operationDispatchMsgMapper")
public interface OperationDispatchMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String dispatchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(OperationDispatchMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(OperationDispatchMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    OperationDispatchMsg selectByPrimaryKey(String dispatchid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(OperationDispatchMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationdispatchmsg
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(OperationDispatchMsg record);
}