package com.whut.wharf.mapper;

import com.whut.wharf.entity.OperationLogWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("operationLogMapper")
public interface OperationLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(OperationLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationlog
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(OperationLogWithBLOBs record);
}