package com.whut.wharf.mapper;

import com.whut.wharf.entity.OperationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("operationInfoMapper")
public interface OperationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    OperationInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(OperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(OperationInfo record);
}