package com.whut.wharf.mapper;

import com.whut.wharf.entity.Pattern;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("patternMapper")
public interface PatternMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pattern
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(Pattern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pattern
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(Pattern record);
}