package com.whut.wharf.mapper;

import com.whut.wharf.entity.PilotPlanInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("pilotPlanInfoMapper")
public interface PilotPlanInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String pioltplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PilotPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PilotPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PilotPlanInfo selectByPrimaryKey(String pioltplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PilotPlanInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplaninfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PilotPlanInfo record);
}