package com.whut.wharf.mapper;

import com.whut.wharf.entity.PilotInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("pilotInfoMapper")
public interface PilotInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PilotInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PilotInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PilotInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PilotInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PilotInfo record);
}