package com.whut.wharf.mapper;

import com.whut.wharf.entity.PilotPlanIdentify;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("pilotPlanIdentifyMapper")
public interface PilotPlanIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplanidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String pioltplanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplanidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PilotPlanIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pilotplanidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PilotPlanIdentify record);
}