package com.whut.wharf.mapper;

import com.whut.wharf.entity.PlotAreaInfoSub;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("plotAreaInfoSubMapper")
public interface PlotAreaInfoSubMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PlotAreaInfoSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PlotAreaInfoSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PlotAreaInfoSub selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PlotAreaInfoSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfosub
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PlotAreaInfoSub record);
}