package com.whut.wharf.mapper;

import com.whut.wharf.entity.PlotAreaInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("plotAreaInfoMapper")
public interface PlotAreaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer areanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PlotAreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PlotAreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PlotAreaInfo selectByPrimaryKey(Integer areanid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PlotAreaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plotareainfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PlotAreaInfo record);
}