package com.whut.wharf.mapper;

import com.whut.wharf.entity.PortRegisterInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("portRegisterInfoMapper")
public interface PortRegisterInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PortRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PortRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PortRegisterInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PortRegisterInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PortRegisterInfo record);
}