package com.whut.wharf.mapper;

import com.whut.wharf.entity.PortRegisterInfoCopy1;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("portRegisterInfoCopy1Mapper")
public interface PortRegisterInfoCopy1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PortRegisterInfoCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PortRegisterInfoCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PortRegisterInfoCopy1 selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PortRegisterInfoCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portregisterinfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PortRegisterInfoCopy1 record);
}