package com.whut.wharf.mapper;

import com.whut.wharf.entity.PortNameCache;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("portNameCacheMapper")
public interface PortNameCacheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(PortNameCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(PortNameCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    PortNameCache selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(PortNameCache record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table portnamecache
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(PortNameCache record);
}