package com.whut.wharf.mapper;

import com.whut.wharf.entity.RegisterRemind;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("registerRemindMapper")
public interface RegisterRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(RegisterRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(RegisterRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    RegisterRemind selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(RegisterRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registerremind
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(RegisterRemind record);
}