package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipTraceInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipTraceInfoMapper")
public interface ShipTraceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiptraceinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipTraceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shiptraceinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipTraceInfo record);
}