package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipInfoMapper")
public interface ShipInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mmsi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipInfo selectByPrimaryKey(Integer mmsi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipInfo record);
}