package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipAgentInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipAgentInfoMapper")
public interface ShipAgentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipAgentInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipagentinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipAgentInfo record);
}