package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipCompanyInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipCompanyInfoMapper")
public interface ShipCompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String shipcompanyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipCompanyInfo selectByPrimaryKey(String shipcompanyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipcompanyinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipCompanyInfo record);
}