package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipOperationData;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipOperationDataMapper")
public interface ShipOperationDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipOperationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipOperationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipOperationData selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipOperationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(ShipOperationData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipoperationdata
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipOperationData record);
}