package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipConnteam;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipConnteamMapper")
public interface ShipConnteamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipConnteam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipConnteam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipConnteam selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipConnteam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipconnteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipConnteam record);
}