package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipInTeam;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipInTeamMapper")
public interface ShipInTeamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String mmsi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipInTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipInTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipInTeam selectByPrimaryKey(String mmsi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipInTeam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipinteam
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipInTeam record);
}