package com.whut.wharf.mapper;

import com.whut.wharf.entity.ShipImageInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("shipImageInfoMapper")
public interface ShipImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(ShipImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(ShipImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    ShipImageInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(ShipImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shipimageinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(ShipImageInfo record);
}