package com.whut.wharf.mapper;

import com.whut.wharf.entity.SysInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("sysInfoMapper")
public interface SysInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String apptoken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(SysInfo record);
}