package com.whut.wharf.mapper;

import com.whut.wharf.entity.TideInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tideInfoMapper")
public interface TideInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer tidenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TideInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TideInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TideInfo selectByPrimaryKey(Integer tidenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TideInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tideinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TideInfo record);
}