package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugApplyIdentify;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugApplyIdentifyMapper")
public interface TugApplyIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugApplyIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugApplyIdentify record);
}