package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugApplyOpeContent;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugApplyOpeContentMapper")
public interface TugApplyOpeContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugApplyOpeContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugApplyOpeContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugApplyOpeContent selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugApplyOpeContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyopecontent
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugApplyOpeContent record);
}