package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugApplyOperationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugApplyOperationInfoMapper")
public interface TugApplyOperationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugApplyOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugApplyOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugApplyOperationInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugApplyOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugApplyOperationInfo record);
}