package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugApplyMsgInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugApplyMsgInfoMapper")
public interface TugApplyMsgInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugApplyMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugApplyMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugApplyMsgInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugApplyMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TugApplyMsgInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplymsginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugApplyMsgInfo record);
}