package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugApplyInorExportInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugApplyInorExportInfoMapper")
public interface TugApplyInorExportInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugApplyInorExportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugApplyInorExportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugApplyInorExportInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugApplyInorExportInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugapplyinorexportinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugApplyInorExportInfo record);
}