package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugBerthCost;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugBerthCostMapper")
public interface TugBerthCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugBerthCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugBerthCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugBerthCost selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugBerthCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugberthcost
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugBerthCost record);
}