package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugCostConsultInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugCostConsultInfoMapper")
public interface TugCostConsultInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugCostConsultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugCostConsultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugCostConsultInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugCostConsultInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostconsultinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugCostConsultInfo record);
}