package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugCostInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugCostInfoMapper")
public interface TugCostInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String voyageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugCostInfo selectByPrimaryKey(String voyageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugcostinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugCostInfo record);
}