package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugDispatchDriverInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugDispatchDriverInfoMapper")
public interface TugDispatchDriverInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugDispatchDriverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugDispatchDriverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugDispatchDriverInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugDispatchDriverInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugDispatchDriverInfo record);
}