package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugDividedInfoDel;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugDividedInfoDelMapper")
public interface TugDividedInfoDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdividedinfodel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugDividedInfoDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdividedinfodel
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugDividedInfoDel record);
}