package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugDispatchDriverInfoCopy;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugDispatchDriverInfoCopyMapper")
public interface TugDispatchDriverInfoCopyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugDispatchDriverInfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugDispatchDriverInfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugDispatchDriverInfoCopy selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugDispatchDriverInfoCopy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchdriverinfo_copy
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugDispatchDriverInfoCopy record);
}