package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugDispatchUserInfo;
import com.whut.wharf.entity.TugDispatchUserInfoKey;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugDispatchUserInfoMapper")
public interface TugDispatchUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(TugDispatchUserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugDispatchUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugDispatchUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugDispatchUserInfo selectByPrimaryKey(TugDispatchUserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugDispatchUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugdispatchuserinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugDispatchUserInfo record);
}