package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugFileInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugFileInfoMapper")
public interface TugFileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugFileInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugFileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugfileinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugFileInfo record);
}