package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugInfoMapper")
public interface TugInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TugInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugInfo record);
}