package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugInWhichPlan;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugInWhichPlanMapper")
public interface TugInWhichPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugInWhichPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugInWhichPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugInWhichPlan selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugInWhichPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginwhichplan
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugInWhichPlan record);
}