package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugInfoAll;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugInfoAllMapper")
public interface TugInfoAllMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugInfoAll selectByPrimaryKey(String tugname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugInfoAll record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tuginfoall
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugInfoAll record);
}