package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugOperationInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugOperationInfoMapper")
public interface TugOperationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugOperationInfo selectByPrimaryKey(String tugoperationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugOperationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugOperationInfo record);
}