package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugOperationTypeInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugOperationTypeInfoMapper")
public interface TugOperationTypeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugopertypecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugOperationTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugOperationTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugOperationTypeInfo selectByPrimaryKey(String tugopertypecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugOperationTypeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugoperationtypeinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugOperationTypeInfo record);
}