package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugPlanHistoryInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugPlanHistoryInfoMapper")
public interface TugPlanHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugPlanHistoryInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugPlanHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugplanhistoryinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugPlanHistoryInfo record);
}