package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugProposerInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugProposerInfoMapper")
public interface TugProposerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugProposerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugProposerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugProposerInfo selectByPrimaryKey(String tugapplyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugProposerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugproposerinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugProposerInfo record);
}