package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugStateChange;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugStateChangeMapper")
public interface TugStateChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugStateChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugStateChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugStateChange selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugStateChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugstatechange
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugStateChange record);
}