package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugScoreInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugScoreInfoMapper")
public interface TugScoreInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugScoreInfo selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugScoreInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugscoreinfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugScoreInfo record);
}