package com.whut.wharf.mapper;

import com.whut.wharf.entity.TugWokerPoints;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("tugWokerPointsMapper")
public interface TugWokerPointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(TugWokerPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(TugWokerPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    TugWokerPoints selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(TugWokerPoints record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tugwokerpoints
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(TugWokerPoints record);
}