package com.whut.wharf.mapper;

import com.whut.wharf.entity.UnionFull;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("unionFullMapper")
public interface UnionFullMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unionfull
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(UnionFull record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unionfull
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(UnionFull record);
}