package com.whut.wharf.mapper;

import com.whut.wharf.entity.UserLogInfoCopy1;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("userLogInfoCopy1Mapper")
public interface UserLogInfoCopy1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:16:55 CST 2023
     */
    int insert(UserLogInfoCopy1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo_copy1
     *
     * @mbggenerated Sun Dec 03 17:16:55 CST 2023
     */
    int insertSelective(UserLogInfoCopy1 record);
}