package com.whut.wharf.mapper;

import com.whut.wharf.entity.UserInfoTug;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("userInfoTugMapper")
public interface UserInfoTugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(UserInfoTug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(UserInfoTug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    UserInfoTug selectByPrimaryKey(Integer mkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(UserInfoTug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfotug
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(UserInfoTug record);
}