package com.whut.wharf.mapper;

import com.whut.wharf.entity.UserLogInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("userLogInfoMapper")
public interface UserLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(Integer logkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(UserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(UserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    UserLogInfo selectByPrimaryKey(Integer logkey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKeySelective(UserLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userloginfo
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int updateByPrimaryKey(UserLogInfo record);
}