package com.whut.wharf.mapper;

import com.whut.wharf.entity.VoyageIdentify;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository("voyageIdentifyMapper")
public interface VoyageIdentifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voyageidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int deleteByPrimaryKey(String voyageid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voyageidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insert(VoyageIdentify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table voyageidentify
     *
     * @mbggenerated Sun Dec 03 17:13:30 CST 2023
     */
    int insertSelective(VoyageIdentify record);
}